name: build_mac.sh MacOS Ton Desktop wallet compile
on: [push]
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - name: Check out current repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install xz-5.0.5.tar.gz
      run: |
        mkdir -p Libraries/macos
        cd Libraries/macos
        mv ../../xz-5.0.5.tar.gz .
        tar -xvf xz-5.0.5.tar.gz
    - name: Install MacOS wallet
      run: |
        chmod +x build_mac.sh
        ./build_mac.sh
    - name: Find & copy binaries
      run: |
        mkdir artifacts
        ls -lart wallet-desktop/out
        ls -lart wallet-desktop/out/Release
        cp -R wallet-desktop/out/Release artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: newton-macos-desktop-wallet
        path: artifacts
