name: build_mac.sh MacOS Ton Desktop wallet compile
on: [push]
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - name: Check out current repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install MacOS wallet
      run: |
        chmod +x build_mac.sh
        ./build_mac.sh
    - name: Find & copy binaries
      run: |
        mkdir artifacts
        chmod +x wallet-desktop/out/Release/Wallet.app/Contents/MacOS/Wallet
        cp wallet-desktop/out/Release/Wallet.app/Contents/MacOS/Wallet artifacts/
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: newton-macos-desktop-wallet
        path: artifacts
