name: C/C++ CI Win

on: [push]

defaults:
  run:
    shell: cmd
    
jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out my repository 1
        uses: actions/checkout@v2
        
      - name: Check out my repository 2
        uses: actions/checkout@v2
        with:
          repository: danmar/cppcheck
          path: cppcheck
          
      - name: Check out my repository 3
        uses: actions/checkout@v2
        with:
          repository: newton-blockchain/ton
          path: ton
          submodules:  'recursive'
                    
      - name: dir
        run: |
          dir
                    
      - name: cd cppcheck
        run: |
          cd cppcheck

      - name: dir
        run: |
          dir
          
      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
                            
      - name: dir
        run: |
          dir
          
      - name: build ton
        run: |
          set root=%cd%
          echo %root%
          cd ton
          mkdir build
          cd build
          cmake -A Win32 -DZLIB_INCLUDE_DIR=%root%\zlib.1.2.8_x64\include\zlib -DZLIB_LIBRARY=%root%\zlib.1.2.8_x64\lib\zlib\zlibstatic.lib -DOPENSSL_FOUND=1 -DOPENSSL_INCLUDE_DIR=%root%\openssl_1_1_1\include -DOPENSSL_CRYPTO_LIBRARY=%root%\openssl_1_1_1\out32\libcrypto.lib -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
