name: C/C++ CI Win

on: [push]

defaults:
  run:
    shell: cmd
    
jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Check out cppcheck repository
        uses: actions/checkout@v2
        with:
          repository: danmar/cppcheck
          path: cppcheck

      - name: Check out zlib repository
        uses: actions/checkout@v2
        with:
          repository: desktop-app/zlib
          path: zlib
          
      - name: Check out newton blockchain repository
        uses: actions/checkout@v2
        with:
          repository: newton-blockchain/ton
          path: ton
          submodules:  'recursive'
                    
      - name: dir
        run: |
          dir
                    
      - name: cd cppcheck
        run: |
          cd cppcheck

      - name: dir
        run: |
          dir
          
      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
                
      - name: Compile zlib
        run: |
          cd zlib\contrib\vstudio\vc14
          msbuild zlibstat.vcxproj /property:Configuration=Debug
          msbuild zlibstat.vcxproj /property:Configuration=ReleaseWithoutAsm          
          
      - name: dir
        run: |
          dir
          
      - name: build ton
        run: |
          set root=%cd%
          echo %root%
          cd ton
          mkdir build
          cd build
          cmake -A Win32 -DZLIB_FOUND=1 -DZLIB_INCLUDE_DIR=%root%\zlib -DZLIB_LIBRARY=%root%\zlib\contrib\vstudio\vc14\x86\ZlibStatReleaseWithoutAsm\zlibstat.lib -DOPENSSL_FOUND=1 -DOPENSSL_INCLUDE_DIR=%root%\opensll_1_1_1-stable\include -DOPENSSL_CRYPTO_LIBRARY=%root%\opensll_1_1_1-stable\out32\libcrypto.lib -DCMAKE_CXX_FLAGS_RELEASE="/DZLIB_WINAPI /MT /Ob2" -DCMAKE_C_FLAGS_RELEASE="/MT /Ob2" -DCMAKE_EXE_LINKER_FLAGS="/SAFESEH:NO Ws2_32.lib Gdi32.lib Advapi32.lib Crypt32.lib User32.lib" -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
