name: C/C++ CI Win

on: [push]

defaults:
  run:
    shell: cmd
    
jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Check out cppcheck repository
        uses: actions/checkout@v2
        with:
          repository: danmar/cppcheck
          path: cppcheck

      - name: Check out zlib repository
        uses: actions/checkout@v2
        with:
          repository: desktop-app/zlib
          path: zlib
          
      - name: Check out newton blockchain repository
        uses: actions/checkout@v2
        with:
          repository: newton-blockchain/ton
          path: ton
          submodules:  'recursive'
                   
      - name: find & copy binaries
        run: |
          cd ton
          mkdir artifactsa
          for /f %a in ('dir *.exe /b /a /s') do copy /Y %a artifactsa
          
      - name: dir
        run: |
          dir
                    
      - name: cd cppcheck
        run: |
          cd cppcheck

      - name: dir
        run: |
          dir
          
      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
                
      - name: Compile zlib
        run: |
          cd zlib\contrib\vstudio\vc14
          msbuild zlibstat.vcxproj /property:Configuration=Debug
          msbuild zlibstat.vcxproj /property:Configuration=ReleaseWithoutAsm          
          
      - name: Install OpenSSL
        run: |
          curl -o openssl.msi https://slproweb.com/download/Win64OpenSSL-1_1_1i.msi
          msiexec /i openssl.msi /quiet /qn /norestart
          
      - name: build ton
        run: |
          set root=%cd%
          echo %root%
          cd ton
          mkdir build
          cd build
          cmake -DZLIB_FOUND=1 -DZLIB_INCLUDE_DIR=%root%\zlib.1.2.8_x64\include\zlib -DZLIB_LIBRARY=%root%\zlib.1.2.8_x64\lib\zlib\zlibstatic.lib -DCMAKE_CXX_FLAGS="/DTD_WINDOWS=1 /EHsc /bigobj /NODEFAULTLIB:library /W1" -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
        continue-on-error: true          
          
      - name: Show executables
        run: |
          cd ton
          cd build
          dir *.exe /a-D /S /B
          
      - name: find & copy binaries
        run: |
          cd ton
          cd build
          mkdir artifactsa
          for /f %a in ('dir *.exe /b /a /s') do copy /Y %a artifactsa
          
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-win-binaries
          path: artifacts
