name: C/C++ CI Ubuntu 18.04 x86-64 Newton Desktop wallet compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Create directories
        run: |
          sudo chmod +x compile.sh
          sudo ./compile.sh
