name: MacOS Ton Desktop wallet compile

on: [push]

jobs:
  build:

    runs-on: macos-10.15
    steps:
    - name: Check out current repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Check out ton wallet-desktop
      uses: actions/checkout@v2
      with:
        repository: newton-blockchain/wallet-desktop
        path: wallet-desktop
    - name: Install xz-5.0.5.tar.gz
      run: |
        mkdir -p Libraries/macos
        cd Libraries/macos
        mv ../../xz-5.0.5.tar.gz .
        tar -xvf xz-5.0.5.tar.gz

    - name: Install homebrew
      run: |
        MAKE_THREADS_CNT=-j8
        MACOSX_DEPLOYMENT_TARGET=10.12
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        sudo chown -R `whoami`:admin /usr/local/bin
        sudo chown -R `whoami`:admin /usr/local/share
        sudo chown -R `whoami`:admin /usr/local/opt
#      echo asdf
#      sudo chown -R $(whoami) /usr/local/opt
#      echo doctor run
#      brew doctor
#     continue-on-error: true 

    - name: Install wallet
      run: |
        brew install automake fdk-aac git lame libass libtool libvorbis libvpx ninja opus sdl shtool texi2html theora wget x264 xvid yasm pkg-config

        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        ls -altr
        
        mkdir ThirdParty
        cd ThirdParty

        git clone https://github.com/desktop-app/patches.git
        cd patches
        git checkout 10aeaf6
        cd ../
        git clone https://chromium.googlesource.com/external/gyp
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH="$PWD/depot_tools:$PATH"
        cd gyp
        git checkout 9f2a7bb1
        git apply ../patches/gyp.diff
        ./setup.py build
        sudo ./setup.py install
        cd ../..

        cd Libraries/macos
        LibrariesPath=`pwd`
        
        git clone https://github.com/desktop-app/patches.git
        cd patches
        git checkout 10aeaf6
        cd ..
        git clone --branch 0.10.0 https://github.com/ericniebler/range-v3

        cd xz-5.0.5
        CFLAGS="-mmacosx-version-min=10.12" LDFLAGS="-mmacosx-version-min=10.12" ./configure --prefix=/usr/local/macos
        make $MAKE_THREADS_CNT
        sudo make install
        cd ..
        
        git clone https://github.com/desktop-app/zlib.git
        cd zlib
        CFLAGS="-mmacosx-version-min=10.12 -Werror=unguarded-availability-new" LDFLAGS="-mmacosx-version-min=10.12" ./configure --prefix=/usr/local/macos
        make $MAKE_THREADS_CNT
        sudo make install
        cd ..

        git clone https://github.com/openssl/openssl openssl_1_1_1
        cd openssl_1_1_1
        git checkout OpenSSL_1_1_1-stable
        ./Configure --prefix=/usr/local/macos darwin64-x86_64-cc -static -mmacosx-version-min=10.12
        make build_libs $MAKE_THREADS_CNT
        cd ..

        git clone https://chromium.googlesource.com/crashpad/crashpad.git
        cd crashpad
        git checkout feb3aa3923
        git apply ../../patches/crashpad.diff
        cd third_party/mini_chromium
        git clone https://chromium.googlesource.com/chromium/mini_chromium
        cd mini_chromium
        git checkout 7c5b0c1ab4
        git apply ../../../../../patches/mini_chromium.diff
        cd ../../gtest
        git clone https://chromium.googlesource.com/external/github.com/google/googletest gtest
        cd gtest
        git checkout d62d6c6556
        cd ../../..

        build/gyp_crashpad.py -Dmac_deployment_target=10.10
        ninja -C out/Debug
        ninja -C out/Release
        cd ..
