name: C/C++ CI Win

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out my repository
        uses: actions/checkout@v2
        with:
          repository: danmar/cppcheck
          
      - name: dir
        run: |
          dir

      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
                  
      - name: dir
        run: |
          dir
          
      - name: Install PCRE
        run: |
          curl -fsSL https://ftp.pcre.org/pub/pcre/pcre-8.44.zip -o pcre-8.44.zip
          7z x pcre-8.44.zip
          cd pcre-8.44
          cmake . -G "Visual Studio 16 2019" -A x64
          msbuild -m PCRE.sln /p:Configuration=Release /p:Platform=x64
          dir
          dir Release
          dir x64
          dir x64\Release
          copy pcre.h ..\externals
          copy Release\pcre.lib ..\externals\pcre64.lib

      - name: dir
        run: |
          dir
          
      - name: Install Z3 library
        run: |
          curl -fsSL https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-win.zip -o z3-4.8.10-win.zip
          7z x z3-4.8.10-win.zip -oexternals -r -y
          move externals\z3-4.8.10-x64-win externals\z3

      - name: dir
        run: |
          dir
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: 'qtcharts'
          
      - name: dir
        run: |
          dir          
          
      - name: Build GUI x64 release
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" 
          cd gui
          qmake HAVE_QCHART=yes
          nmake release
      
      - name: Deploy GUI
        run: |
          windeployqt Build\gui
          del Build\gui\cppcheck-gui.ilk
          del Build\gui\cppcheck-gui.pdb
          
      - name: Build CLI x64 debug configuration using MSBuild
        run: msbuild -m cppcheck.sln /p:Configuration=Debug-PCRE /p:Platform=x64

      - name: Run Debug test
        run: .\bin\debug\testrunner.exe

      - name: Build x64 release configuration using MSBuild
        run: msbuild -m cppcheck.sln /p:Configuration=Release-PCRE /p:Platform=x64

      - name: Run Release test
        run: .\bin\testrunner.exe
