name: C/C++ CI Win

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check out my repository
        uses: actions/checkout@v2
        with:
          repository: danmar/cppcheck
