name: C/C++ CI Win

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check out my repository
        uses: actions/checkout@v2
        with:
          repository: danmar/cppcheck
          
      - name: dir
        run: |
          dir

      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
                  
      - name: dir
        run: |
          dir
          
      - name: Install PCRE
        env:
          # see https://www.pcre.org/original/changelog.txt
          PCRE_VERSION: 8.44  
        run: |
          curl -fsSL https://ftp.pcre.org/pub/pcre/pcre-%PCRE_VERSION%.zip -o pcre-%PCRE_VERSION%.zip
          7z x pcre-%PCRE_VERSION%.zip
          cd pcre-%PCRE_VERSION%
          cmake . -G "Visual Studio 16 2019" -A x64
          msbuild -m PCRE.sln /p:Configuration=Release /p:Platform=x64
          dir
          dir Release
          dir x64
          dir x64\Release
          copy pcre.h ..\externals
          copy Release\pcre.lib ..\externals\pcre64.lib

      - name: dir
        run: |
          dir
          
      - name: Install Z3 library
        run: |
          curl -fsSL https://github.com/Z3Prover/z3/releases/download/z3-%Z3_VERSION%/z3-%Z3_VERSION%-x64-win.zip -o z3-%Z3_VERSION%-win.zip
          7z x z3-%Z3_VERSION%-win.zip -oexternals -r -y
          move externals\z3-%Z3_VERSION%-x64-win externals\z3
        env:
          # see https://github.com/Z3Prover/z3/releases:  
          Z3_VERSION: 4.8.10

      - name: dir
        run: |
          dir
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: 'qtcharts'
          
      - name: dir
        run: |
          dir          
          
