name: C/C++ CI Windows x64 Desktop newton wallet compile

on: [push]

defaults:
  run:
    shell: cmd
    
jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Install Third Party
        run: |
          mkdir ThirdParty
          cd ThirdParty
          curl -o install.msi https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.msi
          msiexec /i install.msi /quiet /qn /norestart TARGETDIR="%cd%\Strawberry" INSTALLDIR="%cd%\Strawberry" INSTALLFOLDER="%cd%\Strawberry"
          del install.msi

          curl -o install.msi https://www.python.org/ftp/python/2.7.8/python-2.7.8.amd64.msi
          msiexec /i install.msi /quiet /qn /norestart TARGETDIR="%cd%\Python27"
          del install.msi

          curl -o install.msi -LO https://github.com/Kitware/CMake/releases/download/v3.19.4/cmake-3.19.4-win64-x64.msi
          msiexec /i install.msi /quiet /qn /norestart TARGETDIR="%cd%\mycmake" INSTALLDIR="%cd%\mycmake" INSTALLFOLDER="%cd%\mycmake"
          del install.msi

          curl -o nasm.zip https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip
          unzip nasm.zip -d NASM
          del nasm.zip

          curl -o yasm.zip http://www.tortall.net/projects/yasm/releases/vsyasm-1.3.0-win64.zip
          unzip yasm.zip -d yasm
          del yasm.zip

          curl -o ninja.zip -LO https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip
          unzip ninja.zip -d Ninja
          del ninja.zip

          curl -o jom.zip http://www.mirrorservice.org/sites/download.qt-project.org/official_releases/jom/jom_1_1_3.zip
          unzip jom.zip -d jom
          del jom.zip
        
          dir
          
          tree
