name: C/C++ CI bat Windows x86
on: [push]

defaults:
   run:
    shell: cmd
    
jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Run batch file
        run: |
          dir "C:\Program Files (x86)\Microsoft Visual Studio\"
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2017"
        
      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[15,16)'
  
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x86   
          
      - name: Run batch file
        run: install_full_with_calls.bat
