name: C/C++ CI bat Windows x86
on: [push]

defaults:
   run:
    shell: cmd
    
jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v2
        
      - name: Install visual studio 2019
        run: | 
            Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            choco install visualstudio2019community
        shell: pwsh

      - name: Run batch file
        run: |
          dir "C:\Program Files (x86)\Microsoft Visual Studio\"
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build"
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
        
#      - name: Setup msbuild.exe
#        uses: microsoft/setup-msbuild@v1.0.2
  
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x86

      - name: Run batch file
        run:  |
          install_full_with_calls.bat
